version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"  
    depends_on:
      - redis
      - postgres
    container_name: express_ap

  redis:
    image: redis:7
    container_name: redis_serve

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
