version: '3.8'

services:
  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - backend_network

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - database
    networks:
      - frontend_network
      - backend_network

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - frontend_network

networks:
  frontend_network:
  backend_network:
