version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: express_app
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_server
