# zadanie 2 
# version: '3.8'

# services:
#   db:
#     image: mongo:4.1.13
#     container_name: db
#     ports:
#       - "27019:27017"
#     volumes:
#       - mongo_data:/data/db
#     networks:
#       - net_A

#   server:
#     build: ./server
#     container_name: server
#     ports:
#       - "3003:3003"
#     networks:
#       - net_A
#     depends_on:
#       - db

# volumes:
#   mongo_data:

# networks:
#   net_A:
#     driver: bridge

# zadanie 3 
version: '3.8'

services:
  db:
    image: mongo:${MONGO_VERSION}
    container_name: db
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - net_A

  server:
    build: ./server
    container_name: server
    ports:
      - "3003:3003"
    networks:
      - net_A
    depends_on:
      - db

volumes:
  mongo_data:

networks:
  net_A:
    driver: bridge
